spring.datasource.url=jdbc:sqlite:database/media_rater.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

db.url=jdbc:sqlite:database/media_rater.db
db.driver=org.sqlite.JDBC
db.user=
db.password=

# db.url=jdbc:postgresql://localhost:5432/media_rater.db
# db.driver=org.postgresql.Driver
# db.user=postgres
# db.password=your_secure_password