db.url=jdbc:sqlite:database/media_rater.db
db.driver=org.sqlite.JDBC
db.user=
db.password=

# db.url=jdbc:postgresql://localhost:5432/media_rater.db
# db.driver=org.postgresql.Driver
# db.user=postgres
# db.password=your_secure_password